version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bot
      - MONGO_INITDB_ROOT_PASSWORD=kuski
      - MONGO_INITDB_DATABASE=kusoki
  kuski:
    container_name: kuski
    image: morozoffnor/kusochkibot:latest
    restart: always
    depends_on:
      - mongo
    environment:
      - CHATID=-961496177
      - PRIZEEVERY="0 0 0 * * *"
      - COCKSIZECOOLDOWN=3600000
      - BOTTOKEN=5992286838:AAH-Jz_BL2bbvtVatX2aibMp87KU5Keqo3w
      - MONGOURL=mongodb://bot:kuski@mongo:27017/kuski
      - OPENAPITOKEN=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