name: Build image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release/**'
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          driver: docker-container
          context: .
          platforms: linux/amd64,linux/arm64
          push: false