name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            docker pull morozoffnor/kusochkibot:${{ github.event.inputs.tag }}
            cd /${{ secrets.SSH_USER }}/kuski && docker compose up -d
      
