name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
      - run: ssh ${{ steps.ssh.outputs.SERVER }} docker pull morozoffnor/kusochkibot:${{ github.event.inputs.tag }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} 'cd /${{ secrets.SSH_USER }}/kuski && docker compose up -d'
