name: Build and deploy (latest)

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --save-dev
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/kusochkibot:latest \
            --platform linux/amd64,linux/arm64 .
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - id: ssh
#        uses: invi5H/ssh-action@v1
#        with:
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_PORT: ${{ secrets.SSH_PORT }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#          SSH_KEY: ${{ secrets.SSH_KEY }}
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} docker pull morozoffnor/kusochkibot
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} 'cd /home/${{ secrets.SSH_USER }}/containers/kusochkibot && docker-compose up -d'

