name: Build and deploy (latest)

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kusochkibot:latest
            ghcr.io/${{ github.repository_owner }}/kusochkibot:latest
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - id: ssh
#        uses: invi5H/ssh-action@v1
#        with:
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_PORT: ${{ secrets.SSH_PORT }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#          SSH_KEY: ${{ secrets.SSH_KEY }}
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} docker pull morozoffnor/kusochkibot
#      - run: ssh ${{ steps.ssh.outputs.SERVER }} 'cd /home/${{ secrets.SSH_USER }}/containers/kusochkibot && docker-compose up -d'

